services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "7861:7861"
    networks:
      - shared_align_network
    restart: unless-stopped
    environment:
      DB_HOST: laravel-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: laravel
    volumes:
      - uploads_data:/app/uploads

networks:
  shared_align_network:
    external: true
    name: shared_alignment_network

volumes:
  uploads_data:
